import { boolean, date, integer, jsonb, numeric, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core"

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("emailVerified").notNull().default(false), image: text("image"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expiresAt").notNull(), token: text("token").notNull().unique(), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow(), ipAddress: text("ipAddress"), userAgent: text("userAgent"), userId: text("userId").notNull() })
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("accountId").notNull(), providerId: text("providerId").notNull(), userId: text("userId").notNull(), accessToken: text("accessToken"), refreshToken: text("refreshToken"), idToken: text("idToken"), accessTokenExpiresAt: timestamp("accessTokenExpiresAt"), refreshTokenExpiresAt: timestamp("refreshTokenExpiresAt"), scope: text("scope"), password: text("password"), createdAt: timestamp("createdAt").notNull().defaultNow(), updatedAt: timestamp("updatedAt").notNull().defaultNow() })
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expiresAt").notNull(), createdAt: timestamp("createdAt").defaultNow(), updatedAt: timestamp("updatedAt").defaultNow() })

export const profiles = pgTable("platform_profiles", { id: text("id").primaryKey(), role: text("role").notNull(), approvalStatus: text("approval_status").notNull().default("pending"), businessName: text("business_name").notNull(), phone: text("phone"), address: text("address"), gstin: text("gstin"), licenseNumber: text("license_number"), metadata: jsonb("metadata").notNull().default({}), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow() })
export const medicines = pgTable("medicines", { id: serial("id").primaryKey(), distributorId: text("distributor_id").notNull(), name: text("name").notNull(), genericName: text("generic_name"), sku: text("sku"), category: text("category"), packSize: text("pack_size"), mrp: numeric("mrp", { precision: 12, scale: 2 }).notNull().default("0"), wholesalePrice: numeric("wholesale_price", { precision: 12, scale: 2 }).notNull().default("0"), taxRate: numeric("tax_rate", { precision: 5, scale: 2 }).notNull().default("0"), isActive: boolean("is_active").notNull().default(true), createdAt: timestamp("created_at").notNull().defaultNow() })
export const medicineRequests = pgTable("medicine_requests", { id: serial("id").primaryKey(), pharmacyId: text("pharmacy_id").notNull(), medicineName: text("medicine_name").notNull(), requestType: text("request_type").notNull(), quantity: integer("quantity"), notes: text("notes"), status: text("status").notNull().default("open"), createdAt: timestamp("created_at").notNull().defaultNow() })
export const customers = pgTable("pharmacy_customers", { id: serial("id").primaryKey(), pharmacyId: text("pharmacy_id").notNull(), name: text("name").notNull(), phone: text("phone"), gstin: text("gstin"), openingBalance: numeric("opening_balance", { precision: 12, scale: 2 }).notNull().default("0"), createdAt: timestamp("created_at").notNull().defaultNow() })
