import type { Prisma } from '@prisma/client'

import { formatINR } from '@/lib/money'
import { SITE } from '@/lib/site'
import { StatusBadge } from '@/components/dashboard/ui'

type InvoicePayload = Prisma.InvoiceGetPayload<{
  include: {
    order: {
      include: {
        items: { include: { medicine: true } }
        pharmacy: true
        distributor: true
      }
    }
  }
}>

export function InvoiceView({ invoice }: { invoice: InvoicePayload }) {
  const { order } = invoice
  return (
    <div id="invoice-doc" className="mx-auto max-w-3xl rounded-xl border border-border bg-white p-8 text-sm text-zinc-900 print:border-0 print:p-0">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-lg font-bold">{SITE.name}</p>
          <p className="text-zinc-500">B2B tax invoice</p>
        </div>
        <div className="text-right">
          <p className="font-semibold">{invoice.invoiceNumber}</p>
          <p className="text-zinc-500">{invoice.invoiceDate.toLocaleDateString()}</p>
          <StatusBadge status={invoice.paymentStatus} />
        </div>
      </div>

      <div className="mt-6 grid grid-cols-2 gap-6">
        <div>
          <p className="text-xs uppercase text-zinc-400">Seller (distributor)</p>
          <p className="font-medium">{order.distributor.companyName}</p>
          <p className="text-zinc-600">
            {order.distributor.addressLine1}, {order.distributor.city}, {order.distributor.state} {order.distributor.pincode}
          </p>
          {order.distributor.gstNumber ? <p className="text-zinc-600">GSTIN: {order.distributor.gstNumber}</p> : null}
        </div>
        <div>
          <p className="text-xs uppercase text-zinc-400">Buyer (pharmacy)</p>
          <p className="font-medium">{order.pharmacy.pharmacyName}</p>
          <p className="text-zinc-600">
            {order.pharmacy.addressLine1}, {order.pharmacy.city}, {order.pharmacy.state} {order.pharmacy.pincode}
          </p>
          {order.pharmacy.gstNumber ? <p className="text-zinc-600">GSTIN: {order.pharmacy.gstNumber}</p> : null}
        </div>
      </div>

      <table className="mt-6 w-full border-collapse text-xs">
        <thead>
          <tr className="border-y border-zinc-300 text-left">
            <th className="py-2">#</th>
            <th className="py-2">Medicine</th>
            <th className="py-2">Batch</th>
            <th className="py-2 text-right">Qty</th>
            <th className="py-2 text-right">Rate</th>
            <th className="py-2 text-right">GST%</th>
            <th className="py-2 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {order.items.map((it, i) => (
            <tr key={it.id} className="border-b border-zinc-200">
              <td className="py-2">{i + 1}</td>
              <td className="py-2">{it.medicine.name}{it.medicine.strength ? ` ${it.medicine.strength}` : ''}</td>
              <td className="py-2">{it.batchNumber ?? '—'}</td>
              <td className="py-2 text-right">{it.quantity}</td>
              <td className="py-2 text-right">{formatINR(it.unitPrice)}</td>
              <td className="py-2 text-right">{Number(it.gstRate)}</td>
              <td className="py-2 text-right">{formatINR(it.lineTotal)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-4 flex justify-end">
        <dl className="w-64 space-y-1">
          <div className="flex justify-between"><dt className="text-zinc-500">Subtotal</dt><dd>{formatINR(invoice.subtotal)}</dd></div>
          <div className="flex justify-between"><dt className="text-zinc-500">GST</dt><dd>{formatINR(invoice.taxAmount)}</dd></div>
          <div className="flex justify-between border-t border-zinc-300 pt-1 font-semibold">
            <dt>Total</dt><dd>{formatINR(invoice.totalAmount)}</dd>
          </div>
        </dl>
      </div>

      <p className="mt-8 text-xs text-zinc-400">
        Generated by {SITE.name}. This is a marketplace-facilitated invoice between the buyer and seller named above.
      </p>
    </div>
  )
}
