"use client"
import { useState } from "react"
import { ClipboardList, FileText, LayoutDashboard, LogOut, Package, Search, Settings, Store, Upload, UserCheck, Users } from "lucide-react"
import { authClient } from "@/lib/auth-client"
import { useRouter } from "next/navigation"
import { PortalWorkbench } from "@/components/portal-workbench"

const menus = { pharmacy: [{ label: "Overview", icon: LayoutDashboard }, { label: "Medicine catalog", icon: Package }, { label: "Bulk orders", icon: ClipboardList }, { label: "Demand requests", icon: Search }, { label: "Billing & ledger", icon: FileText }, { label: "Customers", icon: Users }], distributor: [{ label: "Overview", icon: LayoutDashboard }, { label: "Upload medicines", icon: Upload }, { label: "Inventory", icon: Package }, { label: "Pharmacy orders", icon: ClipboardList }, { label: "Demand requests", icon: Search }, { label: "Business settings", icon: Settings }], admin: [{ label: "Overview", icon: LayoutDashboard }, { label: "Approval queue", icon: UserCheck }, { label: "Medicine catalog", icon: Package }, { label: "Orders", icon: ClipboardList }, { label: "Audit log", icon: FileText }] } as const

export function PortalShell({ name, email, role }: { name: string; email: string; role: "pharmacy" | "distributor" | "admin" }) {
  const router = useRouter()
  const [active, setActive] = useState("Overview")
  const nav = menus[role]
  const roleLabel = role === "pharmacy" ? "Pharmacy workspace" : role === "distributor" ? "Distributor workspace" : "Admin workspace"
  return <div className="flex min-h-screen bg-muted/30"><aside className="hidden w-64 shrink-0 border-r border-border bg-background p-5 lg:flex lg:flex-col"><div className="flex items-center gap-3 font-semibold"><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><Store className="size-5" /></span>LoveMedix B2B</div><nav className="mt-10 space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActive(label)} className={`flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm font-medium ${active === label ? "bg-accent text-accent-foreground" : "text-muted-foreground hover:bg-muted"}`}><Icon className="size-4" />{label}</button>)}</nav><button onClick={async () => { await authClient.signOut(); router.push("/"); router.refresh() }} className="mt-auto flex items-center gap-3 px-3 py-2 text-sm font-medium text-muted-foreground"><LogOut className="size-4" />Sign out</button></aside><main className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b border-border bg-background px-5 sm:px-8"><div><p className="text-sm text-muted-foreground">{roleLabel}</p><h1 className="font-semibold">{active}</h1></div><div className="text-right"><p className="text-sm font-medium">{name}</p><p className="text-xs text-muted-foreground">{email}</p></div></header><div className="page-container py-8"><section className="mb-6 rounded-lg bg-primary p-6 text-primary-foreground sm:p-8"><p className="text-sm font-medium text-primary-foreground/75">Verified {role} account</p><h2 className="mt-2 text-3xl font-semibold">{role === "pharmacy" ? "Procure smarter. Serve better." : role === "distributor" ? "Move quality medicines faster." : "Keep the network trusted."}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-primary-foreground/75">{role === "pharmacy" ? "Your verified procurement workspace for bulk medicines, supplier requests, customer billing, and shop operations." : role === "distributor" ? "Publish your catalog, manage compliant inventory, and fulfill verified pharmacy demand from one workspace." : "Review organizations, maintain the medicine network, and keep every transaction accountable."}</p></section><PortalWorkbench role={role} /></div></main></div>
}
